### ISSUE TITLE
Projects, Project Risk/Health should only show active projects

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/GeoForce#201]
Only active projects, those without a past enddate should be shown. All projects should be in the system for historical date searches.

**Comment by apollolm** [comment]
Currently, the code checks for 'phase__c == 1 thru 5'.   Just to confirm, we only want 2 - 5 for projects?

**Comment by dalekunce** [comment]
We only want phase 2 thru 4 for active
We should still have have the ETL pull all the data and just sort it on the fly.
