### ISSUE TITLE
NGINX: Caching & Compression

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/GeoForce#205]
We should be doing caching in NGINX rather than NodeJS. NGINX is very sophisticated in this regard, and it will simplify Chubbs. This will greatly reduce server load on Chubbs and improve stability.

We also can configure NGINX to do deflate/gzip compression for us. This will solve #98

**Comment by dalekunce** [comment]
did you guys ever get around to doing this?

**Comment by apollolm** [comment]
No.  However, the bulk of the transactions that were happening before (the GeoJSON stuff) is no longer happening. The vector tiles are now coming from a CDN. In-memory caching still happens for BBOX lookups of geometry, details requests and breadcrumb requests for 1 day.
