### ISSUE TITLE
panning to other Earths causes breadcrumbs and bboxes to be incorrect

### ISSUE THREAD

**Issue by apollolm** [AmericanRedCross/GeoForce#209]
starting at the default Earth view, if you pan to the earth to the left or right of it, stuff stops working because the tilebounds become nonsensical.

Either resolve this uisng Nick's modulus method, or tell Leaflet not to allow other Earths.  That's a setting isn't it?

**Comment by dalekunce** [comment]
Is this still an issue with the vector tiles.
