### ISSUE TITLE
filter by business unit

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/GeoForce#232]

**Comment by dalekunce** [comment]
haven't seen any work on this. This is high priority for me.

**Comment by apollolm** [comment]
Can you refresh my memory regarding this one?  Which theme is this for?  Is business unit a column in the project or disaster tables?

**Comment by dalekunce** [comment]
project, business units are things like AMEE, Africa, IROC, IHL, RFL, etc.
