### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by apollolm** [AmericanRedCross/GeoForce#234]
https vs http is bombing.

**Comment by apollolm** [comment]
Also - because print server can't authenticate, the print server needs to be associated with/part of the geo.redcross.org session.

**Comment by dalekunce** [comment]
Can we close this issue now that #290 is closed?

**Comment by dalekunce** [comment]
Why is the printing still going to print.spatialdev I thought this feature was rolled into GeoForce?

**Comment by apollolm** [comment]
I did roll print into GeoForce.  But found out that I can't run print as a new route in GeoForce.  It needs to be on a separate port or server.  Also,  EC2 machines don't internally now about their public facing IP, so calling print on http://54.187.215.30/mapfolio when the print service is at http://54.187.215.30:3005 would fail.  
Given the time restrictions, I decided to keep it on our public service for now.

**Comment by dalekunce** [comment]
set up a seperate server.
