### ISSUE TITLE
Add Org and Staff ECOS Layers

### ISSUE THREAD

**Issue by apollolm** [AmericanRedCross/GeoForce#239]
Use .jpg as style reference.
![image](https://cloud.githubusercontent.com/assets/144543/5532349/cde471f4-89ea-11e4-8daf-a55a55e33e6c.png)

**Comment by apollolm** [comment]
I don't see an Organization or Staff entity in ECOS on prod (when I look in Schema Builder).  Where is this data located?

**Comment by apollolm** [comment]
I see "Related Organization", which ties to Project table. 
There is also a Project Staffing table, but doesn't seem to tie to project. 
Do these sound right?

**Comment by apollolm** [comment]
In ECOS Query Editor, select project__c, organization__c, name from related_organization__c returns 0 results.  Going to shelve this one probably unless we identify a data source.

**Comment by dalekunce** [comment]
confirmed this isn't possible with existing ECOS setup.
