### ISSUE TITLE
always format numbers with thousands comma separators

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/GeoForce#247]
Mostly it does this but sometimes fields could use a thousands-comma-separator (see Total ARC Cash Contribution field, second from the bottom)

![screen shot 2015-03-03 at 10 00 13 pm](https://cloud.githubusercontent.com/assets/4806884/6477343/cc7641b0-c1f0-11e4-8617-eb1374886e86.png)

took the following screenshot, realized i should've captured more screen, then couldn't find it again

![screen shot 2015-03-03 at 9 46 21 pm](https://cloud.githubusercontent.com/assets/4806884/6477289/d3355280-c1ef-11e4-897f-2f9e036f42b6.png)

**Comment by apollolm** [comment]
I took care of the ARC Cash Contribution item, but I'm not finding the approved budget reference.  In which details panel does this value exist?
