### ISSUE TITLE
sort disasters list? (by date?)

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/GeoForce#248]
listing of disasters seems random. order them in some way?

![screen shot 2015-03-03 at 9 41 34 pm](https://cloud.githubusercontent.com/assets/4806884/6477412/a0f6e3a4-c1f1-11e4-8398-0e5695f526d3.png)
![screen shot 2015-03-03 at 9 41 48 pm](https://cloud.githubusercontent.com/assets/4806884/6477413/a10391c6-c1f1-11e4-9b3e-754d19befde0.png)

**Comment by dalekunce** [comment]
Order disasters by:
- Active
- Monitoring
- Inactive
