### ISSUE TITLE
not "official" favicon?

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/GeoForce#251]
not sure it matters (or if it's intentional) but the favicon is different from redcross.org

![screen shot 2015-03-03 at 10 16 37 pm](https://cloud.githubusercontent.com/assets/4806884/6477584/211b317e-c1f3-11e4-8a57-a26d63fea598.png)

**Comment by dalekunce** [comment]
@danbjoseph submit the real favicon as a PR.

**Comment by hallahan** [comment]
:thumbsup:
