### ISSUE TITLE
Listing disasters in order of date, not alphabetical

### ISSUE THREAD

**Issue by cwilkason** [AmericanRedCross/GeoForce#252]
When clicking in a country, the list of disasters needs to be in order of date (highest - lowest) rather than alphabetical. 

Example: When you clicked on Mozambique, the list of disasters reads:
Inactive Mozambique Floods-2013
Active Malawi, Mozambique Floods-2015

It needs to be:
Active Malawi, Mozambique Floods-2015
Inactive Mozambique Floods-2013

**Comment by danbjoseph** [comment]
see also #248

**Comment by apollolm** [comment]
Should they be ordered by date, or by status (Active, Monitoring, Inactive?)

**Comment by dalekunce** [comment]
both :) status by date.
