### ISSUE TITLE
Filters for disasters

### ISSUE THREAD

**Issue by cwilkason** [AmericanRedCross/GeoForce#256]
Currently there are no filters on disasters. Can we discuss which ones should be available? Also, we have to be able to click on all of the countries to see what previous contributions there have been. Currently, we can only click on active/monitored disasters.

**Comment by danielduhh** [comment]
You can currently filter by any disaster_type__c. Each of these types are grouped by category__c (Biological, Geophysical, Human Related, Hydrometeorlogical, & Technological). Clicking on each category will open a dropdown menu and display a list the selected category's disaster_type__c. 

Displaying all 54 types would clutter the panel so I decided to group them by category; Let me know what you think

![screen shot 2015-03-24 at 4 59 21 pm](https://cloud.githubusercontent.com/assets/1947857/6815465/2e00b828-d247-11e4-8716-8f7455ab050c.png)

**Comment by dalekunce** [comment]
I like it. Lets add a type ahead search as well so you can query for the disaster(s) you want without having to hunt for them.
