### ISSUE TITLE
Fields to take out in RFA

### ISSUE THREAD

**Issue by cwilkason** [AmericanRedCross/GeoForce#259]
--Beneficiaries Reached Households
--Beneficiaries reached individuals
--beneficiaries targeted households
--created by ID
--Disaster name (only because it is a weird id)
--Deleted
--Last modified by ID
--latest checklist
--title of request for assistance
--sf_id
--showRfa
--there are two "total ARC Cash Contribution on RFA" fields - why?

**Comment by apollolm** [comment]
The 2 total ARC Cash Contribution fields are actually 2 different fields.  ECOS' label for each is the same.  This labeling is read from ECOS metadata.  
The first field is called total_arc_cash_contribution_on_rfa__c
The second field is called total_arc_contributions__c

Shall I keep them both in?

**Comment by cwilkason** [comment]
No, you can take out the second one. Could we also convert the first one to currency?
