### ISSUE TITLE
Unclear/duplicate indicator fields in projects theme

### ISSUE THREAD

**Issue by devinercolano** [AmericanRedCross/GeoForce#280]
Within the Projects theme under the indicator field, the following indicators are unclear or duplicates:

**USA**
Systems and Technology ARCT FY15
Duplicates
-- %of ISD staff who log in to ECOS at least every 2 weeks
-- #of response or long-term projects supported by GIS

FY15 RFL Outreach and Training Program with ARCT indicators
Duplicates
-- Public Inquiry themes 
-- Geographic distribution of public inquiries

Instructors in Top 20 Regions
Duplicates
-- %of participants who report understanding key concepts of Module 1
-- %of participants who understand the 4 principles of IHL
-- %of participants who understand DPH

RFL-Phone Project-Arizona New Mexico El Paso Texas Gulf Coast, RFL - Phone Projects -Tucson
Unclear indicator tags (indicators with same tag name and different information within)
-- #family phone calls
-- #of Phone Calls 

**MEXICO**
RFL -Phone Projects -El Paso
duplicate indicators
-- #phone calls

**BELIZE**
FY 15 Saving Lives in the Caribbean (SLIC)
-- Duplicate project name

Saving Lives in the Caribbean (SLIC) Program: 
#people participating in training, by sex
-- unclear indicators

Resilience in the Americas (IPA/RITA)
#of youth trained
-- unclear indicators

**EL SALVADOR**
Building Resilience in Chaparrastique Volcano Affected Communities, El Salvador
#people participating in training, aggregated by sex
-- unclear indicators

**COSTA RICA**
Building Resilience in Puntarenas, Costa Rica
#of people attending launch meeting
-- non distinctive labeling

#people trained who retain skills and knowledge after two months
-- duplicates

**JAMAICA**
FY 15 saving lives in the carbon SLIC
#people trained in preparedness, mitigation, management, by sex
-- duplicates and also unclear names **[SAME IN BAHAMAS, SAINT LUCIA, and GUYANA]**

#people passing final exams or receiving certificates, by sex
-- unclear naming

Saving Lives in the Caribbean (SLIC) Program **[SAME IN BAHAMAS, SAINT LUCIA, and GUYANA]**
#people participating in training, by sex
-- unclear naming

**BAHAMAS**
Resilience in the Americas (IPA/RITA) in Bahamas
%youth 15-29 report condom use[female]
-- unclear naming

Saving Lives in the Caribbean (SLIC) Program
#people participating in training, by sex
-- unclear naming

Sit Kitts and Nevis, Antigua and Barbuda, Dominica, Saint Lucia, Saint Vincent & the Grenadines, barbados, Grenada, Trinidad and Tobago, Chile, Argentina, Guyana, Senegal, Guinea, Sierra Leone, Liberia, Côte d’Ivoire, Ghana, Nigeria, Uganda, Kenya, Ethiopia, Malta, Israel, Palestine, Lebanon, Syria, Iceland, Ireland, Switzerland, Czech Republic,  Sweden, Ukraine, New Zeeland, Australia, Singapore, Hong Kong, China, Indonesia, Philippines, Vietnam, Myanmar, Mexico, Jamaica, Bahamas
First Aid and Hazard App Program
-- #of first aid apps in development and  #of live hazard apps
-- -- unclear naming

**COLUMBIA**
Resilience in the Americas (RITA) in Columbia
%NS managed project following phases suggested by PMDPro
-- unclear naming

FY15 Resilience in the Americas (RITA) Program
seems like a duplicate project name
	
**ECUADOR**
Duplicate/excessive project naming
-- FY 2015 Capable Partners
-- FY15 Ecuador OD RFA Capable Partners
	
%NS managed project following phases suggested by PMDPro
-- unclear naming 

**PERU**
Duplicate project naming
-- Disney Pillowcase Program (Phase II) 2014, 
-- Disney Pillowcase Project (Phase II) - Peru

**DOMINICAN REPUBLIC & THAILAND**
BRACES (Model Program) 
Unclear naming
-- #of community members trained
-- %of national societies with branch contingency plans. (R)
	
Camp Autonomization through the FRC
%camps WASH infrastructures working & self-managed at EOP
-- duplicates

Shelter Retrofit for Rental through CARE
#of IDP train on IGA
-- unclear naming
	
Rubble Removal and Demolition through JPHRO
#red houses completely demolished
-- unclear naming

ZRCS BRACES Phase II (Model Project)
-- unclear naming

Economic Development and Livelihoods through Mercy Corps (LAMIKA Pillar 2)
#youth enrolled in internship program, complete internship
-- duplicates and unclear naming

LAMIKA Program
%beneficiaries have improved access to education/ healthcare
-- duplicates

Health Service Delivery through HOPE
#patients seen by mobile clinics, # of mother’s club established
-- unclear naming
#of children referred to Borgne
-- 2 duplicates

**MALI & INDIA**
[is this someone else's test?]
Test 2.6 deployment by Enzigma
-- 4

**NAMIBIA**
FY15 Building Resilient African Communities (BRACES) in
#of CDRMC members who have engaged in capacity building trainings
-- unclear naming

**ZAMBIA**
FY15 Building Resilient African Communities (BRACES) in Namibia
#of CDRMC members who have engaged in capacity building trainings
-- duplicates and unclear naming

**ZIMBABWE**
FY15 Zimbabwe Urban Disaster Risk Reduction (UDRR)
Duplicates
-- #community members trained to conduct a VCA
-- #of communities that have completed a VCA
-- #micro projects implemented based on community action plans

**RWANDA**
FY15 Nyaruguru Resilience Project in Rwanda -Duhuze imbaraga, twiyubaka
%of the target volunteers in Nyaruguru local and district branches tr
-- unclear naming

**TANZANIA**
FY15 Tanzania Integrated HIV and AIDS
#adults 18-59 ill for 3≤months in past 12mos received support
-- unclear naming

#beneficiaries reached by TWC prevention education
-- unclear naming and duplicates
	
FY15 Building Community Resilience in Tanzania
Duplicates
-- #of TRCS project staff trained in project management
-- #of TRCS project staff trained in community mobilization/engagement
-- #comm committees linked to tech support resources in health & WatSan

BRACES (Model Program) (AND SYRIA)
Unclear naming
-- #of community members trained
-- %of National Societies with branch contingency plans. (R )

ZRCS BRACES Phase II (Model Project) (also Syria)
-- unclear labels

**ARMENA**
FY15 Regional Health Initiative (RHI) in Armenia
Unclear Labels
-- #of volunteers actively participating in the project realization
-- %of staff/volunteers (total number) participated in the tra
-- %of teachers with correct answers on 80 % and more of questions of

FY15 Regional Health Initiative for Eurasia (RHI) Program
unclear labeling
-- #of people reached through HIV prevention/treatment services
-- #NS staff and volunteers received project management training
	
**BELARUS**
FY15 Organizational Development (OD) in Belarus with ARCT
Duplicates and unclear naming
-- %of readiness of approved by HQ standardized reporting forms
-- #trained stuff among regional managers, governing and financi, 
-- #of PLHIV who demonstrate awareness, 
-- #of vitamins disseminated, # of people reached through HIV prevention/treatment services, 
-- #NS staff and volunteers received project management training

**UKRAINE**
FY15 Regional Health Initiative (RHI) in Ukraine
#of NS staff trained in M&E
-- duplicates
%of RC small grants recipients demonstrate increased capacity in M&E
-- unclear labels
#of NS staff trained in program management
-- duplicates and unclear labels

FY15 Regional Health Initiative (RHI) in Russia [and Russia]
%trained specialists and volunteers who conducted 3 or more events in
-- unclear labels
#of trainees, who successfully completed Trainings of Level I - II (
-- some duplicates and unclear labels

FY15 Regional Health Initiative for Eurasia (RHI) Program [and Russia]
#NS staff and volunteers received project management training
-- unclear labels
#of people reached through HIV prevention/treatment services
-- duplicates and unclear labels

**INDONESIA**
Coastal Community Resilience and Disaster Risk Reduction in Indonesia
#of safe and resilient community
-- duplicates and unclear labels

Wonogiri Integrated Health - DRR in Indonesia
#of complete and timely monthly project activity report submitted
-- unclear labels

Greater Jakarta Disaster Risk Reduction
#of branches which have at least 5 DRR-CRM Facilitators
-- duplicates and unclear labels

**PHILLIIPPINES**
Integrated Recovery Intervention in Tolosa, Philippines with Spanish Red Cross
#schools have access to rehabilitated/constructed communal latrines
-- unclear labels
#families improved habitability through safer & adequate shelter
-- unclear labels

Early Recovery Assistance to Populations Affected by Typhoon Haiyan - GRC N.Cebu
#households reached by community-based health services.
-- duplicates, unclear labeling
#households provided with shelter repair assistance.
-- unclear labeling

Early Recovery Assistance to Populations Affected by Typhoon Haiyan - GRC Leyte
Duplicates and unclear labels
-- #community facilities provided improved water & sanitation facilities, 
-- #households reached by community-based health services

**VIETNAM**
HIV Project in Vietnam
%PLHIV clients on ARVs who report adherence to their ARV regimen
-- unclear labels

**NEPAL**
Community Action for Disaster Response (CADRE) in Nepal
#of people CADRE trained in disaster prep, mitigation and management
-- unclear labels

**KYRGYZSTAN**
FY15 Organizational Development (OD) in Kyrgyzstan with ARCT
Volunteer data base developed, 
Volunteer data base developed
-- duplicate
Annual resource mobilization plans have been developed with considerat
-- duplicates and unclear labels

**TURKMENISTAN**
FY15 Prepare Central Asia (PCA) in Turkmenistan
Duplicates and unclear labels
-- #of project staff and volunteers from HQ and branch trained in NSM, 
-- #of schoolchildren trained by trained schoolteachers
	
**KAZAKSHSTAN**
FY15 Prepare Central Asia (PCA) in Kazakhstan
#of project staff from HQ and branch trained in FA TOT
-- unclear labels and duplicates
#project staff and volunteers from HQ and branch training in NSM
-- unclear labels

FY15 Organizational Development (OD) in Kazakhstan with ARCT
#of branches with completed revision of the HR system
-- unclear labels
%of branches with 100% staff signed the key HR documents
-- duplicate

FY15 Regional Health Initiative (RHI) in Kazakhstan
unclear labels
-- #of coaching or mentoring sessions held, 
-- %of RC branches demonstrate capacity in program management (PM)

FY15 Regional Health Initiative for Eurasia (RHI) Program
#NS staff and volunteers received project management training
-- unclear labels
#of people reached through HIV prevention/treatment services
-- duplicates and unclear labels

**Comment by apollolm** [comment]
I'll close this issue.  This has to do with Red Cross data coming from Salesforce.  Not our domain.
