### ISSUE TITLE
Indistinct Legend Values and Smal Icons **Enhancement**

### ISSUE THREAD

**Issue by devinercolano** [AmericanRedCross/GeoForce#281]
In the Disaster Type theme all the values in the legend are the same color and it is difficult to discern what the icons are. Maybe those icons could be included in the legend for clarity.

**Comment by danielduhh** [comment]
This enhancement has been addressed in commit: https://github.com/AmericanRedCross/GeoForce/commit/5c1d0d5eea99930b4e21f7ad787899306937d936
