### ISSUE TITLE
Innactive Layers

### ISSUE THREAD

**Issue by devinercolano** [AmericanRedCross/GeoForce#288]
In the Layers section on the left under the Search tab the following overlays do not display anything:

NOAA Air Temperature
MODIS Landcover 2011
Theme (Badge Off)
themeLayers

The following layers work:

arcregionextents
Cloud Cover
countryextents
GADM0
GADM1
GADM2
GDACS: Global Disaster Alert and Coordination System
LAC Communities
Precipitation
Precipitation (Classic)
Pressure
Pressure Contour
Rain
Rain (Classic)
Snow
Temperature
USGS Realtime Earthquakes Feed (Week)
Wind

**Comment by dalekunce** [comment]
Let's get rid of layers that don't work.
