### ISSUE TITLE
Export image returns an incomplete picture

### ISSUE THREAD

**Issue by devinercolano** [AmericanRedCross/GeoForce#290]
Using the export facility in the toolbar in the upper right corner, I tried to export the current map but the result did not seem complete:
![exportimage](https://cloud.githubusercontent.com/assets/4064770/7191282/3ba674e8-e441-11e4-8282-02afa2ecadb9.jpg)

**Comment by danielduhh** [comment]
Merge #234

**Comment by danielduhh** [comment]
Duplicate of issue #234
