### ISSUE TITLE
'Show More Details' in secondary tab is default

### ISSUE THREAD

**Issue by devinercolano** [AmericanRedCross/GeoForce#291]
When a value in the second tab of the fly in window (Requests for Assistance or Indicators tabs) is clicked it's already displaying the 'Show More Details' option- like it's stuck there. It seems like 'Show Less Details' is never activated.

**Comment by danielduhh** [comment]
The 'Show More Details' button only filters lists of details; excluding request, indicators, risk, and status. Therefore we should disable or hide this button when one of those nav tabs is active
