### ISSUE TITLE
Formatted fields

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/GeoForce#299]
Some fields are still not human readable.

![screen shot 2015-04-21 at 5 48 13 am](https://cloud.githubusercontent.com/assets/1913857/7249678/1b9a4ede-e7ea-11e4-8659-d2763fc7eb5f.png)

**Comment by apollolm** [comment]
need to make sure the .gitignored /GeoAngular/app/succubus_gitignore/*.json files make it across.  They are generated by Succubus on Prod.
